export const GENERATED_HEADER_MARKERS = [
  'do not edit',
  'code generated',
  '@generated',
  'automatically generated',
  'auto-generated',
  'this file is generated',
  'this file was generated',
  'generated by',
  '<auto-generated>',
  'autogenerated by',
  'grpc-tools',
  'protobuf',
  'swagger codegen',
  'openapi generator',
  'source map url=',
  'sourcemappingurl=',
];

export const VENDOR_PATH_SEGMENTS = [
  'vendor/',
  'third_party/',
  'thirdparty/',
  'deps/',
  'extern/',
  'external/',
  'bundled/',
];
