import { describe, it, expect } from 'vitest';
import { SemanticChunker } from '../src/chunker/index.js';
import { LanguageDetector } from '../src/languages/index.js';
import { FileClassifier } from '../src/scanner/classifier.js';
import { SymbolExtractor } from '../src/symbols/index.js';

describe('Phase 2 & 3 Core Tests', () => {
  it('should detect languages accurately', () => {
    expect(LanguageDetector.detect('src/app.ts').language).toBe('typescript');
    expect(LanguageDetector.detect('src/components/Button.tsx').language).toBe('tsx');
    expect(LanguageDetector.detect('main.py').language).toBe('python');
    expect(LanguageDetector.detect('server.go').language).toBe('go');
    expect(LanguageDetector.detect('Cargo.toml').language).toBe('rust');
    expect(LanguageDetector.detect('Dockerfile').language).toBe('dockerfile');
    expect(LanguageDetector.detect('script', '#!/usr/bin/env python3\nprint(1)').language).toBe(
      'python',
    );
  });

  it('should classify generated and binary files', () => {
    const binBuffer = Buffer.from([0x00, 0x01, 0x02, 0x03]);
    expect(FileClassifier.isBinary(binBuffer)).toBe(true);

    const textBuffer = Buffer.from('console.log("hello world");');
    expect(FileClassifier.isBinary(textBuffer)).toBe(false);

    const genContent = '// @generated by protobuf\nexport const x = 1;';
    expect(FileClassifier.isGenerated(genContent, 'proto.ts')).toBe(true);
  });

  it('should extract TypeScript classes, methods, and hooks with hierarchy', () => {
    const code = `
import { useState } from 'react';
import { AuthService } from './auth.service';

export class UserService {
  private id: string;

  constructor() {}

  public async getUser(id: string): Promise<User> {
    return { id };
  }
}

export function useAuth() {
  return useState(null);
}
`;

    const { symbols, dependencies } = SymbolExtractor.extract('src/user.ts', 'typescript', code);
    expect(symbols.length).toBeGreaterThanOrEqual(2);

    const userClass = symbols.find((s) => s.name === 'UserService' && s.type === 'class');
    expect(userClass).toBeDefined();

    const getUserMethod = symbols.find((s) => s.name === 'getUser' && s.type === 'method');
    expect(getUserMethod).toBeDefined();
    expect(getUserMethod?.parentId).toBe(userClass?.id);

    const useAuthHook = symbols.find((s) => s.name === 'useAuth' && s.type === 'hook');
    expect(useAuthHook).toBeDefined();

    expect(dependencies.length).toBe(2);
    expect(dependencies.some((d) => d.specifier === 'react')).toBe(true);
    expect(dependencies.some((d) => d.specifier === './auth.service')).toBe(true);
  });

  it('should produce deterministic chunks that retain hashes across line shifts', () => {
    const chunker = new SemanticChunker();

    const codeV1 = `
export function add(a: number, b: number): number {
  return a + b;
}
`;

    // Same function shifted down by 10 empty lines
    const codeV2 = `
// Some new top comments
// Line 2
// Line 3

export function add(a: number, b: number): number {
  return a + b;
}
`;

    const symbolsV1 = SymbolExtractor.extract('calc.ts', 'typescript', codeV1).symbols;
    const chunksV1 = chunker.chunk('calc.ts', 'typescript', codeV1, symbolsV1);

    const symbolsV2 = SymbolExtractor.extract('calc.ts', 'typescript', codeV2).symbols;
    const chunksV2 = chunker.chunk('calc.ts', 'typescript', codeV2, symbolsV2);

    const addChunk1 = chunksV1.find((c) => c.symbolName === 'add');
    const addChunk2 = chunksV2.find((c) => c.symbolName === 'add');

    expect(addChunk1).toBeDefined();
    expect(addChunk2).toBeDefined();
    expect(addChunk1?.hash).toBe(addChunk2?.hash);
  });
});
